runtime: python
env: flex
entrypoint: gunicorn -b :$PORT rock-paper-scissors:app
instance_class: F2
runtime_config:
  python_version: 3
   
#[START gae_flex_mysql_env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
     mysql+pymysql://root:1234@/bucketlist?unix_socket=/cloudsql/localhost
 #[END gae_flex_mysql_env]
 
 #[START gae_flex_mysql_settings]
    # Replace project and instance with the values obtained  when configuring your
    # Cloud SQL instance.
beta_settings:
    cloud_sql_instances: localhost
#[END gae_flex_mysql_settings]
handlers:

- url: /templates/
  static_files: index.html
  upload: index\.html

- url: .*
  script: rock-paper-scissors.app
